package model

import (
	"errors"
	"time"

	"github.com/QuantumNous/new-api/common"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

var ErrLotteryDailyLimitReached = errors.New("lottery daily limit reached")

// ErrLotteryQuotaOverflow is returned when crediting the drawn prize would push
// the user's quota past the representable int32 range of the quota column. The
// whole draw is rolled back so a record is never written without a valid credit.
var ErrLotteryQuotaOverflow = errors.New("lottery award would exceed the maximum quota")

// LotteryPrize stores one configurable prize shown on the eight-cell lottery board.
type LotteryPrize struct {
	Id         int       `json:"id" gorm:"primaryKey;autoIncrement"`                             // Primary key generated by the database.
	Code       string    `json:"code" gorm:"type:varchar(32);uniqueIndex;not null"`              // Stable prize code used by API clients and historical snapshots.
	Name       string    `json:"name" gorm:"type:varchar(64);not null"`                          // Display name of the prize tier.
	Label      string    `json:"label" gorm:"type:varchar(128);not null"`                        // User-facing description of the reward.
	Icon       string    `json:"icon" gorm:"type:varchar(16);not null"`                          // Short symbol or number rendered inside the lottery cell.
	Tone       string    `json:"tone" gorm:"type:varchar(16);not null"`                          // Visual tone identifier understood by the frontend.
	Weight      int       `json:"weight" gorm:"not null"`                                         // Positive relative probability weight used for server-side selection.
	QuotaAmount int       `json:"quota_amount" gorm:"not null;default:0"`                         // Quota value credited to the winner's balance when this prize is drawn; 0 means no quota is credited.
	SortOrder  int       `json:"sort_order" gorm:"index:idx_lottery_prize_active_sort;not null"` // One-based position on the eight-cell board.
	Active     bool      `json:"active" gorm:"index:idx_lottery_prize_active_sort;not null"`     // Whether this prize participates in draws.
	CreatedAt  time.Time `json:"created_at" gorm:"not null"`                                     // Time when the prize configuration was created.
	UpdatedAt  time.Time `json:"updated_at" gorm:"not null"`                                     // Time when the prize configuration was last changed.
}

func (LotteryPrize) TableName() string {
	return "lottery_prizes"
}

// LotteryDrawRecord stores the immutable result of one user's daily draw.
type LotteryDrawRecord struct {
	Id          int64     `json:"id" gorm:"primaryKey;autoIncrement"`                                                    // Primary key generated by the database.
	UserId      int       `json:"user_id" gorm:"uniqueIndex:idx_lottery_draw_user_day;not null"`                         // Authenticated New API user ID, unique together with DrawDay.
	DrawDay     string    `json:"draw_day" gorm:"type:varchar(10);uniqueIndex:idx_lottery_draw_user_day;index;not null"` // Business date in YYYY-MM-DD format using Asia/Shanghai.
	DisplayName string    `json:"display_name" gorm:"type:varchar(128);not null"`                                        // Masked username snapshot safe for the public activity list.
	PrizeCode   string    `json:"prize_code" gorm:"type:varchar(32);not null"`                                           // Prize code snapshot at draw time.
	PrizeName   string    `json:"prize_name" gorm:"type:varchar(64);not null"`                                           // Prize tier name snapshot at draw time.
	PrizeLabel  string    `json:"prize_label" gorm:"type:varchar(128);not null"`                                         // Prize reward description snapshot at draw time.
	QuotaAmount int       `json:"quota_amount" gorm:"not null;default:0"`                                                 // Quota value snapshot credited to the user at draw time; 0 means no quota.
	CreatedAt   time.Time `json:"created_at" gorm:"index;not null"`                                                      // UTC-backed timestamp when the draw was recorded.
}

func (LotteryDrawRecord) TableName() string {
	return "draw_records"
}

var defaultLotteryPrizes = []LotteryPrize{
	{Code: "xinghe", Name: "星河入梦", Label: "30 梦火", Icon: "30", Tone: "red", Weight: 1, QuotaAmount: defaultQuotaForUsd(30), SortOrder: 1, Active: true},
	{Code: "yunjian", Name: "云间拾玉", Label: "4 梦火", Icon: "4", Tone: "cream", Weight: 20, QuotaAmount: defaultQuotaForUsd(4), SortOrder: 2, Active: true},
	{Code: "qianzhuo", Name: "浅酌清风", Label: "3 梦火", Icon: "3", Tone: "cream", Weight: 25, QuotaAmount: defaultQuotaForUsd(3), SortOrder: 3, Active: true},
	{Code: "zhenxing", Name: "枕星寻迹", Label: "8 梦火", Icon: "8", Tone: "gold", Weight: 6, QuotaAmount: defaultQuotaForUsd(8), SortOrder: 4, Active: true},
	{Code: "xiandu", Name: "闲渡尘途", Label: "5 梦火", Icon: "5", Tone: "cream", Weight: 12, QuotaAmount: defaultQuotaForUsd(5), SortOrder: 5, Active: true},
	{Code: "moyun", Name: "墨韵笺帖", Label: "10 梦火", Icon: "10", Tone: "gold", Weight: 2, QuotaAmount: defaultQuotaForUsd(10), SortOrder: 6, Active: true},
	{Code: "zhuxia", Name: "烛下拾遗", Label: "9 梦火", Icon: "9", Tone: "gold", Weight: 4, QuotaAmount: defaultQuotaForUsd(9), SortOrder: 7, Active: true},
	{Code: "wanzhou", Name: "晚舟载月", Label: "2 梦火", Icon: "2", Tone: "muted", Weight: 30, QuotaAmount: defaultQuotaForUsd(2), SortOrder: 8, Active: true},
}

// defaultQuotaForUsd converts a USD amount to internal quota units using the
// configured quota-per-unit exchange rate, so default prizes carry the same
// real-world value whether the admin edits them in USD or they are seeded.
func defaultQuotaForUsd(usd float64) int {
	return common.QuotaFromFloat(usd * common.QuotaPerUnit)
}

func initializeLotteryPrizes() error {
	// Insert any missing default prizes and refresh only the display label. The
	// credited quota_amount is intentionally NOT updated on conflict so that any
	// amount the admin has configured is never overwritten by the defaults.
	// Name, weight, active and sorting are also left untouched.
	err := DB.Clauses(clause.OnConflict{
		Columns:   []clause.Column{{Name: "code"}},
		DoUpdates: clause.AssignmentColumns([]string{"label"}),
	}).Create(&defaultLotteryPrizes).Error
	if err != nil {
		return err
	}

	// Remove retired prize codes that are no longer part of the lottery. This
	// covers the legacy "retry" lucky-charm as well as the original
	// first/second/third… tier defaults, which have been fully replaced by the
	// guófēng (国风) prize set defined above. This runs as a one-time migration:
	// once the old rows are gone they are never recreated, and edits to the
	// current prizes stay safe because the upsert above only refreshes the label.
	legacyCodes := []string{"retry", "first", "second", "third", "lucky", "bonus", "special", "small", "thanks"}
	return DB.Where("code IN ?", legacyCodes).Delete(&LotteryPrize{}).Error
}

func LotteryBusinessDay(now time.Time) string {
	return now.In(shanghaiLocation).Format("2006-01-02")
}

func GetActiveLotteryPrizes() ([]LotteryPrize, error) {
	var prizes []LotteryPrize
	err := DB.Where("active = ? AND weight > ?", true, 0).Order("sort_order ASC").Find(&prizes).Error
	return prizes, err
}

func HasLotteryDrawn(userId int, drawDay string) (bool, error) {
	var count int64
	err := DB.Model(&LotteryDrawRecord{}).
		Where("user_id = ? AND draw_day = ?", userId, drawDay).
		Count(&count).Error
	return count > 0, err
}

func CreateLotteryDrawRecord(record *LotteryDrawRecord) error {
	err := DB.Create(record).Error
	if err == nil {
		return nil
	}

	drawn, lookupErr := HasLotteryDrawn(record.UserId, record.DrawDay)
	if lookupErr == nil && drawn {
		return ErrLotteryDailyLimitReached
	}
	return err
}

// CreateLotteryDrawRecordTx atomically inserts a draw record and credits the
// winner's quota inside a single transaction. The check for an existing draw on
// the same business day runs inside the transaction so concurrent draws are
// serialized by the database. If quotaToAdd is positive, it is added to the
// user's quota in the same transaction; a failure in either step rolls back the
// whole operation so a record is never written without its quota being credited
// (and vice versa).
func CreateLotteryDrawRecordTx(userId int, drawDay string, record *LotteryDrawRecord, quotaToAdd int) error {
	err := DB.Transaction(func(tx *gorm.DB) error {
		var count int64
		if err := tx.Model(&LotteryDrawRecord{}).
			Where("user_id = ? AND draw_day = ?", userId, drawDay).
			Count(&count).Error; err != nil {
			return err
		}
		if count > 0 {
			return ErrLotteryDailyLimitReached
		}
		if err := tx.Create(record).Error; err != nil {
			return err
		}
		if quotaToAdd > 0 {
			// Conditional atomic credit: the WHERE guard both (a) rejects a
			// credit that would overflow the int32 quota column
			// (quota <= MaxQuota - award) and (b) requires the user row to
			// still exist. RowsAffected != 1 means one of those failed, so we
			// roll the whole draw back rather than record a win without its
			// quota. common.MaxQuota-quotaToAdd cannot underflow here because
			// quotaToAdd is bounded by MaxQuota at prize-config time.
			res := tx.Model(&User{}).
				Where("id = ? AND quota <= ?", userId, common.MaxQuota-quotaToAdd).
				Update("quota", gorm.Expr("quota + ?", quotaToAdd))
			if res.Error != nil {
				return res.Error
			}
			if res.RowsAffected != 1 {
				return ErrLotteryQuotaOverflow
			}
		}
		return nil
	})
	if err != nil {
		return err
	}
	// The DB write and quota credit are committed atomically; only now do we
	// sync the in-memory/Redis quota cache so the user sees the credited amount
	// immediately. A cache failure does not roll back the committed draw.
	if quotaToAdd > 0 {
		if err := cacheIncrUserQuota(userId, int64(quotaToAdd)); err != nil {
			common.SysLog("failed to increase user quota cache after lottery draw: " + err.Error())
		}
	}
	return nil
}

// GetLotteryDrawRecords returns today's draw records ordered by the credited
// quota descending (so the highest win appears first), falling back to the
// newest draw for equal amounts. It returns all rows for the day.
func GetLotteryDrawRecords(drawDay string) ([]LotteryDrawRecord, error) {
	var records []LotteryDrawRecord
	err := DB.Where("draw_day = ?", drawDay).
		Order("quota_amount DESC, created_at DESC").
		Limit(20).
		Find(&records).Error
	return records, err
}

// GetUserLotteryDrawRecords returns the user's draw records ordered by draw
// time descending. The limit caps the returned rows so the history view can
// scroll within a fixed-height panel.
func GetUserLotteryDrawRecords(userId int, limit int) ([]LotteryDrawRecord, error) {
	var records []LotteryDrawRecord
	err := DB.Where("user_id = ?", userId).
		Order("created_at DESC").
		Limit(limit).
		Find(&records).Error
	return records, err
}

// GetTodayUserDraw returns the user's draw record for the given business day.
// It returns nil when the user has not drawn yet on that day.
func GetTodayUserDraw(userId int, drawDay string) (*LotteryDrawRecord, error) {
	var record LotteryDrawRecord
	err := DB.Where("user_id = ? AND draw_day = ?", userId, drawDay).
		Order("created_at DESC").
		First(&record).Error
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, nil
		}
		return nil, err
	}
	return &record, nil
}

// GetAllLotteryPrizes returns all configured prizes ordered by their board
// position, including inactive ones, for the admin management page.
func GetAllLotteryPrizes() ([]LotteryPrize, error) {
	var prizes []LotteryPrize
	err := DB.Order("sort_order ASC").Find(&prizes).Error
	return prizes, err
}

// CreateLotteryPrize inserts a new prize configuration.
func CreateLotteryPrize(prize *LotteryPrize) error {
	return DB.Create(prize).Error
}

// UpdateLotteryPrize saves changes to an existing prize configuration.
func UpdateLotteryPrize(prize *LotteryPrize) error {
	return DB.Save(prize).Error
}

// DeleteLotteryPrize removes a prize configuration by its primary key.
func DeleteLotteryPrize(id int) error {
	return DB.Delete(&LotteryPrize{}, id).Error
}
