package model

import (
	"errors"
	"time"

	"github.com/QuantumNous/new-api/common"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

var ErrLotteryDailyLimitReached = errors.New("lottery daily limit reached")

// LotteryPrize stores one configurable prize shown on the eight-cell lottery board.
type LotteryPrize struct {
	Id         int       `json:"id" gorm:"primaryKey;autoIncrement"`                             // Primary key generated by the database.
	Code       string    `json:"code" gorm:"type:varchar(32);uniqueIndex;not null"`              // Stable prize code used by API clients and historical snapshots.
	Name       string    `json:"name" gorm:"type:varchar(64);not null"`                          // Display name of the prize tier.
	Label      string    `json:"label" gorm:"type:varchar(128);not null"`                        // User-facing description of the reward.
	Icon       string    `json:"icon" gorm:"type:varchar(16);not null"`                          // Short symbol or number rendered inside the lottery cell.
	Tone       string    `json:"tone" gorm:"type:varchar(16);not null"`                          // Visual tone identifier understood by the frontend.
	Weight      int       `json:"weight" gorm:"not null"`                                         // Positive relative probability weight used for server-side selection.
	QuotaAmount int       `json:"quota_amount" gorm:"not null;default:0"`                         // Quota value credited to the winner's balance when this prize is drawn; 0 means no quota is credited.
	SortOrder  int       `json:"sort_order" gorm:"index:idx_lottery_prize_active_sort;not null"` // One-based position on the eight-cell board.
	Active     bool      `json:"active" gorm:"index:idx_lottery_prize_active_sort;not null"`     // Whether this prize participates in draws.
	CreatedAt  time.Time `json:"created_at" gorm:"not null"`                                     // Time when the prize configuration was created.
	UpdatedAt  time.Time `json:"updated_at" gorm:"not null"`                                     // Time when the prize configuration was last changed.
}

func (LotteryPrize) TableName() string {
	return "lottery_prizes"
}

// LotteryDrawRecord stores the immutable result of one user's daily draw.
type LotteryDrawRecord struct {
	Id          int64     `json:"id" gorm:"primaryKey;autoIncrement"`                                                    // Primary key generated by the database.
	UserId      int       `json:"user_id" gorm:"uniqueIndex:idx_lottery_draw_user_day;not null"`                         // Authenticated New API user ID, unique together with DrawDay.
	DrawDay     string    `json:"draw_day" gorm:"type:varchar(10);uniqueIndex:idx_lottery_draw_user_day;index;not null"` // Business date in YYYY-MM-DD format using Asia/Shanghai.
	DisplayName string    `json:"display_name" gorm:"type:varchar(128);not null"`                                        // Masked username snapshot safe for the public activity list.
	PrizeCode   string    `json:"prize_code" gorm:"type:varchar(32);not null"`                                           // Prize code snapshot at draw time.
	PrizeName   string    `json:"prize_name" gorm:"type:varchar(64);not null"`                                           // Prize tier name snapshot at draw time.
	PrizeLabel  string    `json:"prize_label" gorm:"type:varchar(128);not null"`                                         // Prize reward description snapshot at draw time.
	QuotaAmount int       `json:"quota_amount" gorm:"not null;default:0"`                                                 // Quota value snapshot credited to the user at draw time; 0 means no quota.
	CreatedAt   time.Time `json:"created_at" gorm:"index;not null"`                                                      // UTC-backed timestamp when the draw was recorded.
}

func (LotteryDrawRecord) TableName() string {
	return "draw_records"
}

var defaultLotteryPrizes = []LotteryPrize{
	{Code: "first", Name: "一等奖", Label: "积分 500", Icon: "1", Tone: "red", Weight: 1, QuotaAmount: defaultQuotaForUsd(500), SortOrder: 1, Active: true},
	{Code: "second", Name: "二等奖", Label: "积分 300", Icon: "2", Tone: "gold", Weight: 2, QuotaAmount: defaultQuotaForUsd(300), SortOrder: 2, Active: true},
	{Code: "third", Name: "三等奖", Label: "积分 200", Icon: "3", Tone: "cream", Weight: 4, QuotaAmount: defaultQuotaForUsd(200), SortOrder: 3, Active: true},
	{Code: "lucky", Name: "幸运奖", Label: "积分 100", Icon: "100", Tone: "cream", Weight: 8, QuotaAmount: defaultQuotaForUsd(100), SortOrder: 4, Active: true},
	{Code: "bonus", Name: "奖励奖", Label: "积分 50", Icon: "50", Tone: "cream", Weight: 15, QuotaAmount: defaultQuotaForUsd(50), SortOrder: 5, Active: true},
	{Code: "special", Name: "特别奖", Label: "积分 30", Icon: "30", Tone: "gold", Weight: 20, QuotaAmount: defaultQuotaForUsd(30), SortOrder: 6, Active: true},
	{Code: "small", Name: "微额奖", Label: "积分 10", Icon: "10", Tone: "muted", Weight: 25, QuotaAmount: defaultQuotaForUsd(10), SortOrder: 7, Active: true},
	{Code: "thanks", Name: "谢谢参与", Label: "下次好运", Icon: "-", Tone: "muted", Weight: 25, QuotaAmount: 0, SortOrder: 8, Active: true},
}

// defaultQuotaForUsd converts a USD amount to internal quota units using the
// configured quota-per-unit exchange rate, so default prizes carry the same
// real-world value whether the admin edits them in USD or they are seeded.
func defaultQuotaForUsd(usd float64) int {
	return common.QuotaFromFloat(usd * common.QuotaPerUnit)
}

func initializeLotteryPrizes() error {
	// Insert any missing default prizes and refresh only the display label. The
	// credited quota_amount is intentionally NOT updated on conflict so that any
	// amount the admin has configured is never overwritten by the defaults.
	// Name, weight, active and sorting are also left untouched.
	err := DB.Clauses(clause.OnConflict{
		Columns:   []clause.Column{{Name: "code"}},
		DoUpdates: clause.AssignmentColumns([]string{"label"}),
	}).Create(&defaultLotteryPrizes).Error
	if err != nil {
		return err
	}

	// The legacy "retry" lucky-charm prize (redeem for another draw) is no
	// longer part of the lottery and should be removed from the board.
	return DB.Where("code = ?", "retry").Delete(&LotteryPrize{}).Error
}

func LotteryBusinessDay(now time.Time) string {
	return now.In(shanghaiLocation).Format("2006-01-02")
}

func GetActiveLotteryPrizes() ([]LotteryPrize, error) {
	var prizes []LotteryPrize
	err := DB.Where("active = ? AND weight > ?", true, 0).Order("sort_order ASC").Find(&prizes).Error
	return prizes, err
}

func HasLotteryDrawn(userId int, drawDay string) (bool, error) {
	var count int64
	err := DB.Model(&LotteryDrawRecord{}).
		Where("user_id = ? AND draw_day = ?", userId, drawDay).
		Count(&count).Error
	return count > 0, err
}

func CreateLotteryDrawRecord(record *LotteryDrawRecord) error {
	err := DB.Create(record).Error
	if err == nil {
		return nil
	}

	drawn, lookupErr := HasLotteryDrawn(record.UserId, record.DrawDay)
	if lookupErr == nil && drawn {
		return ErrLotteryDailyLimitReached
	}
	return err
}

// CreateLotteryDrawRecordTx atomically inserts a draw record and credits the
// winner's quota inside a single transaction. The check for an existing draw on
// the same business day runs inside the transaction so concurrent draws are
// serialized by the database. If quotaToAdd is positive, it is added to the
// user's quota in the same transaction; a failure in either step rolls back the
// whole operation so a record is never written without its quota being credited
// (and vice versa).
func CreateLotteryDrawRecordTx(userId int, drawDay string, record *LotteryDrawRecord, quotaToAdd int) error {
	err := DB.Transaction(func(tx *gorm.DB) error {
		var count int64
		if err := tx.Model(&LotteryDrawRecord{}).
			Where("user_id = ? AND draw_day = ?", userId, drawDay).
			Count(&count).Error; err != nil {
			return err
		}
		if count > 0 {
			return ErrLotteryDailyLimitReached
		}
		if err := tx.Create(record).Error; err != nil {
			return err
		}
		if quotaToAdd > 0 {
			if err := tx.Model(&User{}).
				Where("id = ?", userId).
				Update("quota", gorm.Expr("quota + ?", quotaToAdd)).Error; err != nil {
				return err
			}
		}
		return nil
	})
	if err != nil {
		return err
	}
	// The DB write and quota credit are committed atomically; only now do we
	// sync the in-memory/Redis quota cache so the user sees the credited amount
	// immediately. A cache failure does not roll back the committed draw.
	if quotaToAdd > 0 {
		if err := cacheIncrUserQuota(userId, int64(quotaToAdd)); err != nil {
			common.SysLog("failed to increase user quota cache after lottery draw: " + err.Error())
		}
	}
	return nil
}

// GetLotteryDrawRecords returns today's draw records ordered by the credited
// quota descending (so the highest win appears first), falling back to the
// newest draw for equal amounts. It returns all rows for the day.
func GetLotteryDrawRecords(drawDay string) ([]LotteryDrawRecord, error) {
	var records []LotteryDrawRecord
	err := DB.Where("draw_day = ?", drawDay).
		Order("quota_amount DESC, created_at DESC").
		Limit(20).
		Find(&records).Error
	return records, err
}

// GetUserLotteryDrawRecords returns the user's draw records ordered by draw
// time descending. The limit caps the returned rows so the history view can
// scroll within a fixed-height panel.
func GetUserLotteryDrawRecords(userId int, limit int) ([]LotteryDrawRecord, error) {
	var records []LotteryDrawRecord
	err := DB.Where("user_id = ?", userId).
		Order("created_at DESC").
		Limit(limit).
		Find(&records).Error
	return records, err
}

// GetTodayUserDraw returns the user's draw record for the given business day.
// It returns nil when the user has not drawn yet on that day.
func GetTodayUserDraw(userId int, drawDay string) (*LotteryDrawRecord, error) {
	var record LotteryDrawRecord
	err := DB.Where("user_id = ? AND draw_day = ?", userId, drawDay).
		Order("created_at DESC").
		First(&record).Error
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, nil
		}
		return nil, err
	}
	return &record, nil
}

// GetAllLotteryPrizes returns all configured prizes ordered by their board
// position, including inactive ones, for the admin management page.
func GetAllLotteryPrizes() ([]LotteryPrize, error) {
	var prizes []LotteryPrize
	err := DB.Order("sort_order ASC").Find(&prizes).Error
	return prizes, err
}

// CreateLotteryPrize inserts a new prize configuration.
func CreateLotteryPrize(prize *LotteryPrize) error {
	return DB.Create(prize).Error
}

// UpdateLotteryPrize saves changes to an existing prize configuration.
func UpdateLotteryPrize(prize *LotteryPrize) error {
	return DB.Save(prize).Error
}

// DeleteLotteryPrize removes a prize configuration by its primary key.
func DeleteLotteryPrize(id int) error {
	return DB.Delete(&LotteryPrize{}, id).Error
}
